identifier="FactorEras:LuckiusDev"
name="FactorEras"
description="Add more machines and stuff"
authors=["LuckiusDev"]
dependencies=["VoxelEras:DestinyHailstorm"]
entry="factoreras/entry.rhai"
version="0.2.0"
sync=true